sudo: required

services:
  - docker

script:
  - docker build -t finances .
  - docker tag finances ianmartorell/finances:latest
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push ianmartorell/finances:latest
