sudo: required
services:
- docker
script:
- docker build -t finances .
- docker tag finances quay.io/ian/finances
- docker login quay.io -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD"
- docker push quay.io/ian/finances
- mv deploy_key ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- ssh -oStrictHostKeyChecking=no -tl core "$HOST_ADDRESS" "sudo systemctl restart finances"
before_install:
- openssl aes-256-cbc -K $encrypted_73ae7b520f81_key -iv $encrypted_73ae7b520f81_iv
  -in deploy_key.enc -out deploy_key -d
