sudo: required

services:
  - docker

script:
  - docker build -t finances .
  - docker tag finances quay.io/ian/finances
  - docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD"
  - docker push quay.io/ian/finances
